Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      SupplierTemplateConfigs:
        - Name: 模板1
          Url: ros_templates/template.yaml
          PredefinedParameters: []
          AllowedRegions:
            - cn-beijing
            - cn-hangzhou
            - cn-heyuan
    TemplateConfigs:
      - Name: 模板1
        Url: ros_templates/template.yaml
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-heyuan
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      模板1:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo_zh-CN.png
      Locale: zh-CN
      Name: 通义万相 AI 绘画
      ShortDescription: 本服务展示了如何利用自研的通义万相 AIGC 技术在 Web 服务中实现先进的图像生成。其中包括文本到图像、涂鸦转换、人像风格重塑以及人物写真创建等功能。这些能力可以加快艺术家和设计师的创作流程，提高创意效率。同时，也可以在广告营销、教育和游戏开发等多个领域进行应用，以提升内容的视觉表现和用户体验。
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
Artifact: {}
